name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set a lowercase variable for the repository owner
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy youtube-fetch-web \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ghcr-mirror/${{ steps.string.outputs.lowercase }}:latest \
          --region us-central1 \
          --allow-unauthenticated